"""Writes the JSON Schemas under `schemas/` from the contract models, and checks them for drift
(docs/contracts.md, schema generation and drift). `scripts/schemas` runs it:

    python -m trialfolio.contracts.schema_files [--check] [--dir DIR]

Without `--check`, it writes every schema. It never deletes anything: before writing, it refuses
a directory that holds any other file or a subdirectory. With `--check`, it writes nothing: it
compares the directory with the schemas it generates, lists each file that differs, is missing,
or is extra, and exits 1 if there's any. Both ignore hidden entries, such as macOS's `.DS_Store`.
"""

import argparse
import json
import sys
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from functools import cache
from pathlib import Path
from types import MappingProxyType
from typing import Final

from pydantic import BaseModel
from pydantic.json_schema import JsonSchemaMode

from trialfolio.contracts.acknowledgment import AcknowledgmentRecord
from trialfolio.contracts.attempt import AttemptRecord, StartRecord
from trialfolio.contracts.manifest import RunManifest
from trialfolio.contracts.plan import Plan
from trialfolio.contracts.review_configuration import ReviewConfiguration
from trialfolio.contracts.review_manifest import ReviewManifest
from trialfolio.contracts.screen_configuration import ScreenConfiguration
from trialfolio.contracts.summary import JsonSummary, JsonSummaryV1_1
from trialfolio.contracts.tables import DifferencesRow, MetricsRow, SettingsRow

JSON_SCHEMA_DIALECT: Final = "https://json-schema.org/draft/2020-12/schema"


@dataclass(frozen=True)
class SchemaFile:
    """One published schema: its file name, the model it's generated from, and the mode."""

    name: str
    model: type[BaseModel]
    mode: JsonSchemaMode


SCHEMA_FILES: Final = (
    # A configuration is input, so its schema is what validation accepts. Every other contract
    # is written by Trial Folio, so its schema is what serialization writes.
    SchemaFile("screen-configuration-1.0.0.schema.json", ScreenConfiguration, "validation"),
    SchemaFile("review-configuration-1.0.0.schema.json", ReviewConfiguration, "validation"),
    SchemaFile("plan-1.0.0.schema.json", Plan, "serialization"),
    SchemaFile("start-record-1.0.0.schema.json", StartRecord, "serialization"),
    SchemaFile("attempt-record-1.0.0.schema.json", AttemptRecord, "serialization"),
    SchemaFile("run-manifest-1.0.0.schema.json", RunManifest, "serialization"),
    SchemaFile("review-manifest-1.0.0.schema.json", ReviewManifest, "serialization"),
    SchemaFile("metrics-row-1.0.0.schema.json", MetricsRow, "serialization"),
    SchemaFile("settings-row-1.0.0.schema.json", SettingsRow, "serialization"),
    SchemaFile("differences-row-1.0.0.schema.json", DifferencesRow, "serialization"),
    # 1.0.0 is what Trial Folio 0.1.0 writes, kept with its bytes unchanged; 0.2.0 writes 1.1.0.
    SchemaFile("json-summary-1.0.0.schema.json", JsonSummary, "serialization"),
    SchemaFile("json-summary-1.1.0.schema.json", JsonSummaryV1_1, "serialization"),
    SchemaFile("license-acknowledgment.schema.json", AcknowledgmentRecord, "serialization"),
)
"""Every published schema: one for each contract and each schema version that has a reader."""


def render(schema_file: SchemaFile) -> str:
    """Returns the text of one schema file. The `$comment` states the mode, and whether the
    other mode gives a different schema."""
    model = schema_file.model
    schema = model.model_json_schema(mode=schema_file.mode)
    other: JsonSchemaMode = "serialization" if schema_file.mode == "validation" else "validation"
    if schema == model.model_json_schema(mode=other):
        modes = "Validation and serialization modes give the same schema."
    else:
        modes = f"In {other} mode, the schema differs."
    comment = (
        f"Generated by scripts/schemas from {model.__module__}.{model.__qualname__}, in "
        f"{schema_file.mode} mode. {modes} Never edit it by hand."
    )
    document = {"$schema": JSON_SCHEMA_DIALECT, "$comment": comment, **schema}
    return json.dumps(document, indent=2, ensure_ascii=False) + "\n"


@cache
def generate() -> Mapping[str, bytes]:
    """Returns every schema file's bytes, by file name. The models don't change while the process
    runs, so they're generated once."""
    return MappingProxyType(
        {schema_file.name: render(schema_file).encode() for schema_file in SCHEMA_FILES}
    )


def _entries(directory: Path) -> dict[str, Path]:
    if not directory.is_dir():
        return {}
    return {path.name: path for path in directory.iterdir() if not path.name.startswith(".")}


def check(directory: Path) -> list[str]:
    """Compares `directory` with the generated schemas, and returns one line for each file that
    differs, is missing, or is extra. An empty list means no drift."""
    expected = generate()
    present = _entries(directory)
    problems: list[str] = []
    for name, content in expected.items():
        path = present.get(name)
        if path is None:
            problems.append(f"missing: {name}")
        elif not path.is_file() or path.read_bytes() != content:
            problems.append(f"differs: {name}")
    for name in sorted(present.keys() - expected.keys()):
        problems.append(f"extra: {name}/" if present[name].is_dir() else f"extra: {name}")
    return problems


class SchemaDirectoryError(Exception):
    """The directory can't take the schemas as it is. Raised before anything is written."""


def write(directory: Path) -> None:
    """Writes every schema into `directory`. Raises `SchemaDirectoryError`, before writing
    anything, if `directory` isn't a directory, or holds a subdirectory or any other file, so a
    mistaken target never loses a file."""
    expected = generate()
    if not directory.is_dir() and (directory.exists() or directory.is_symlink()):
        raise SchemaDirectoryError(f"{directory} isn't a directory. Choose another --dir.")
    present = _entries(directory)
    folders = sorted(name for name, path in present.items() if path.is_dir())
    if folders:
        raise SchemaDirectoryError(
            f"{directory} holds directories: {', '.join(folders)}. It holds only schema files: "
            "remove them, or choose another --dir."
        )
    extra = sorted(present.keys() - expected.keys())
    if extra:
        raise SchemaDirectoryError(
            f"{directory} holds files that aren't current schemas: {', '.join(extra)}. "
            "Delete each one you've checked is obsolete, or choose another --dir."
        )
    directory.mkdir(parents=True, exist_ok=True)
    for name, content in expected.items():
        (directory / name).write_bytes(content)


def main(argv: Sequence[str] | None = None) -> int:
    """Runs the command line. Returns the exit status."""
    parser = argparse.ArgumentParser(
        prog="scripts/schemas",
        description="Write the JSON Schemas from the contract models, or check them for drift.",
    )
    parser.add_argument("--check", action="store_true", help="compare only; write nothing")
    parser.add_argument("--dir", type=Path, default=Path("schemas"), help="default: schemas")
    arguments = parser.parse_args(argv)
    directory: Path = arguments.dir
    if arguments.check:
        problems = check(directory)
        for problem in problems:
            print(f"schemas: {problem}", file=sys.stderr)
        if problems:
            # Writing never deletes, so an extra entry is the user's to remove first.
            steps: list[str] = []
            if any(problem.startswith("extra: ") for problem in problems):
                steps.append("delete each extra entry you've checked is obsolete")
            if not all(problem.startswith("extra: ") for problem in problems):
                steps.append("run scripts/schemas to regenerate the schemas")
            print(f"schemas: drift found. To fix it, {', then '.join(steps)}.", file=sys.stderr)
            return 1
        print(f"The {len(SCHEMA_FILES)} schemas in {directory} match the models.")
        return 0
    try:
        write(directory)
    except SchemaDirectoryError as error:
        print(f"schemas: {error}", file=sys.stderr)
        return 1
    print(f"Wrote {len(SCHEMA_FILES)} schemas to {directory}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
