"""`scripts/schemas` writes one schema for each contract, and `--check` finds every kind of drift.

Traces to docs/contracts.md, schema generation and drift, and to `scripts/schemas --check` in
release 0.1.0's verification commands. `scripts/check` runs the check on the committed schemas;
these tests check the generator itself, in a temporary directory.
"""

import json
import typing
from pathlib import Path

import pytest

from trialfolio.contracts.schema_files import (
    JSON_SCHEMA_DIALECT,
    SCHEMA_FILES,
    check,
    generate,
    main,
    write,
)


def test_each_schema_names_its_model_and_mode() -> None:
    for name, content in generate().items():
        schema = json.loads(content)
        assert schema["$schema"] == JSON_SCHEMA_DIALECT, name
        assert "Generated by scripts/schemas from trialfolio.contracts." in schema["$comment"]
        assert " mode." in schema["$comment"]


def test_a_versioned_contract_names_its_version() -> None:
    """One file for each contract and each schema version that has a reader."""
    for schema_file in SCHEMA_FILES:
        field = schema_file.model.model_fields.get("schema_version")
        if field is None:
            continue
        (version,) = typing.get_args(field.annotation)
        assert schema_file.name.endswith(f"-{version}.schema.json")


def test_check_passes_after_write(tmp_path: Path) -> None:
    write(tmp_path)

    assert check(tmp_path) == []


def test_check_lists_each_kind_of_drift(tmp_path: Path) -> None:
    write(tmp_path)
    first, second = SCHEMA_FILES[0].name, SCHEMA_FILES[1].name
    (tmp_path / first).write_text("{}\n")
    (tmp_path / second).unlink()
    (tmp_path / "hand-written.schema.json").write_text("{}\n")

    assert check(tmp_path) == [
        f"differs: {first}",
        f"missing: {second}",
        "extra: hand-written.schema.json",
    ]


def test_check_of_a_missing_directory_lists_every_schema(tmp_path: Path) -> None:
    assert check(tmp_path / "absent") == [f"missing: {file.name}" for file in SCHEMA_FILES]


def test_write_replaces_drifted_files_and_removes_others(tmp_path: Path) -> None:
    (tmp_path / SCHEMA_FILES[0].name).write_text("{}\n")
    (tmp_path / "stale.schema.json").write_text("{}\n")

    write(tmp_path)

    assert sorted(path.name for path in tmp_path.iterdir()) == sorted(generate())
    assert check(tmp_path) == []


def test_main_exits_1_on_drift_and_writes_nothing(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert main(["--check", "--dir", str(tmp_path)]) == 1

    assert list(tmp_path.iterdir()) == []
    assert "Run scripts/schemas to regenerate them." in capsys.readouterr().err


def test_main_writes_then_checks_clean(tmp_path: Path) -> None:
    assert main(["--dir", str(tmp_path)]) == 0
    assert main(["--check", "--dir", str(tmp_path)]) == 0
