"""`scripts/schemas` writes one schema for each contract, and `--check` finds every kind of drift.

Traces to docs/contracts.md, schema generation and drift, and to `scripts/schemas --check` in
release 0.1.0's verification commands. `scripts/check` runs the check on the committed schemas;
these tests check the generator itself, in a temporary directory. The JSON summary's tests trace
to release 0.2.0's open question on the summary's version: 1.0.0's schema keeps its bytes, and
1.1.0 only adds to it; and to R03-AC16, as release 0.3.0's open question on the summary's version
settled (D-33): 1.1.0's schema keeps v0.2.0's bytes, and a 1.1.0 summary of each command, with
its version changed, is a valid 1.2.0 summary. R03-T06 wrote 1.2.0's checks, ahead of R03-T11.
"""

import hashlib
import json
import shutil
import subprocess
import typing
from pathlib import Path

import pytest

from tests.support.git import outside_any_repository
from trialfolio.contracts import schema_files
from trialfolio.contracts.schema_files import (
    JSON_SCHEMA_DIALECT,
    SCHEMA_FILES,
    check,
    generate,
    main,
    write,
)
from trialfolio.contracts.summary import JsonSummary, JsonSummaryV1_1, JsonSummaryV1_2


def test_each_schema_names_its_model_and_mode() -> None:
    for name, content in generate().items():
        schema = json.loads(content)
        assert schema["$schema"] == JSON_SCHEMA_DIALECT, name
        assert "Generated by scripts/schemas from trialfolio.contracts." in schema["$comment"]
        assert " mode." in schema["$comment"]


def test_a_versioned_contract_names_its_version() -> None:
    """One file for each contract and each schema version that has a reader."""
    for schema_file in SCHEMA_FILES:
        field = schema_file.model.model_fields.get("schema_version")
        if field is None:
            continue
        (version,) = typing.get_args(field.annotation)
        assert schema_file.name.endswith(f"-{version}.schema.json")


def test_check_passes_after_write(tmp_path: Path) -> None:
    write(tmp_path)

    assert check(tmp_path) == []


def test_check_lists_each_kind_of_drift(tmp_path: Path) -> None:
    write(tmp_path)
    first, second = SCHEMA_FILES[0].name, SCHEMA_FILES[1].name
    (tmp_path / first).write_text("{}\n")
    (tmp_path / second).unlink()
    (tmp_path / "hand-written.schema.json").write_text("{}\n")

    assert check(tmp_path) == [
        f"differs: {first}",
        f"missing: {second}",
        "extra: hand-written.schema.json",
    ]


def test_check_of_a_missing_directory_lists_every_schema(tmp_path: Path) -> None:
    assert check(tmp_path / "absent") == [f"missing: {file.name}" for file in SCHEMA_FILES]


def test_write_replaces_drifted_files(tmp_path: Path) -> None:
    (tmp_path / SCHEMA_FILES[0].name).write_text("{}\n")

    write(tmp_path)

    assert sorted(path.name for path in tmp_path.iterdir()) == sorted(generate())
    assert check(tmp_path) == []


@pytest.mark.parametrize("extra", ["notes.txt", "stale.schema.json"])
def test_write_refuses_unexpected_files_without_changing_anything(
    tmp_path: Path, extra: str, capsys: pytest.CaptureFixture[str]
) -> None:
    """Regression: --dir must never delete unrelated files or partially regenerate schemas."""
    before = {SCHEMA_FILES[0].name: b"{}\n", extra: b"keep me\n"}
    for name, content in before.items():
        (tmp_path / name).write_bytes(content)

    assert main(["--dir", str(tmp_path)]) == 1
    assert "aren't current schemas" in capsys.readouterr().err
    assert {path.name: path.read_bytes() for path in tmp_path.iterdir()} == before


def test_write_refuses_a_file_as_the_directory(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Regression: a mistaken --dir naming a file is refused, not a traceback."""
    target = tmp_path / "README.md"
    target.write_bytes(b"keep me\n")

    assert main(["--dir", str(target)]) == 1
    assert "isn't a directory" in capsys.readouterr().err
    assert target.read_bytes() == b"keep me\n"


def test_a_generation_error_isnt_reported_as_a_directory_problem(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    def broken() -> None:
        raise ValueError("a defect in a model")

    monkeypatch.setattr(schema_files, "generate", broken)

    with pytest.raises(ValueError, match="a defect in a model"):
        main(["--dir", str(tmp_path)])


ROOT = Path(__file__).resolve().parents[2]


@pytest.mark.skipif(shutil.which("sh") is None, reason="scripts/schemas is a POSIX shell script")
def test_script_runs_from_any_directory_and_reads_dir_from_there(tmp_path: Path) -> None:
    """Regression: the script finds the repository from its own location, outside any Git
    repository too, and a relative --dir is relative to the caller's directory."""
    write(tmp_path / "out")
    result = subprocess.run(
        ["sh", str(ROOT / "scripts" / "schemas"), "--check", "--dir", "out"],
        cwd=tmp_path,
        env=outside_any_repository()
        | {"UV_NO_SYNC": "true", "UV_OFFLINE": "true", "UV_NO_ENV_FILE": "true"},
        capture_output=True,
        text=True,
        check=False,
    )

    assert result.returncode == 0, result.stderr
    assert "schemas in out match the models" in result.stdout


def test_git_checkout_preserves_schema_bytes_with_autocrlf(tmp_path: Path) -> None:
    """Regression: a Windows-style Git checkout must pass the byte-for-byte drift check."""
    (tmp_path / ".gitattributes").write_bytes((ROOT / ".gitattributes").read_bytes())
    write(tmp_path / "schemas")
    checkout = tmp_path / "checkout"
    checkout.mkdir()
    for args in (
        ["init", "--quiet"],
        ["-c", "core.autocrlf=false", "add", ".gitattributes", "schemas"],
        ["-c", "core.autocrlf=true", "checkout-index", "--all", f"--prefix={checkout}/"],
    ):
        subprocess.run(
            ["git", *args],
            cwd=tmp_path,
            env=outside_any_repository(),
            check=True,
            capture_output=True,
        )

    assert check(checkout / "schemas") == []


def test_main_exits_1_on_drift_and_writes_nothing(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    assert main(["--check", "--dir", str(tmp_path)]) == 1

    assert list(tmp_path.iterdir()) == []
    assert "To fix it, run scripts/schemas to regenerate the schemas." in capsys.readouterr().err


def test_check_says_to_delete_an_extra_file_by_hand(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    """Regression: writing never deletes, so an extra file alone isn't sent to scripts/schemas."""
    write(tmp_path)
    (tmp_path / "plan-0.9.0.schema.json").write_text("{}\n")

    assert main(["--check", "--dir", str(tmp_path)]) == 1
    error = capsys.readouterr().err
    assert "To fix it, delete each extra entry you've checked is obsolete." in error
    assert "run scripts/schemas" not in error


def test_main_writes_then_checks_clean(tmp_path: Path) -> None:
    assert main(["--dir", str(tmp_path)]) == 0
    assert main(["--check", "--dir", str(tmp_path)]) == 0


def test_hidden_files_are_ignored(tmp_path: Path) -> None:
    """A Finder .DS_Store, for example, is neither drift nor removed."""
    write(tmp_path)
    (tmp_path / ".DS_Store").write_bytes(b"\0")

    assert check(tmp_path) == []
    write(tmp_path)
    assert (tmp_path / ".DS_Store").exists()


def test_a_subdirectory_is_extra_and_stops_writing(
    tmp_path: Path, capsys: pytest.CaptureFixture[str]
) -> None:
    (tmp_path / "old").mkdir()

    assert check(tmp_path)[-1] == "extra: old/"
    assert main(["--dir", str(tmp_path)]) == 1
    assert [path.name for path in tmp_path.iterdir()] == ["old"]
    assert "holds directories: old" in capsys.readouterr().err


# The JSON summary's versions

SUMMARY_1_0_0 = "json-summary-1.0.0.schema.json"
SUMMARY_1_1_0 = "json-summary-1.1.0.schema.json"
SUMMARY_1_2_0 = "json-summary-1.2.0.schema.json"

SUMMARY_1_0_0_SHA256 = "0ce25e981d49a06d433fd68dd15bc15e50d929ca37604a7af79f5b51bcfdb67d"
"""The SHA-256 of `schemas/json-summary-1.0.0.schema.json` at the tag v0.1.0, written by hand:
`git show v0.1.0:schemas/json-summary-1.0.0.schema.json | shasum -a 256`."""


def test_the_json_summary_1_0_0_schema_keeps_v0_1_0_s_bytes() -> None:
    """It says what Trial Folio 0.1.0 prints, for scripts written against it."""
    committed = (ROOT / "schemas" / SUMMARY_1_0_0).read_bytes()

    assert hashlib.sha256(generate()[SUMMARY_1_0_0]).hexdigest() == SUMMARY_1_0_0_SHA256
    assert hashlib.sha256(committed).hexdigest() == SUMMARY_1_0_0_SHA256


PLAN_HASH = "sha256:" + "a1" * 32
CASE_ID = "case-0123456789abcdef"
ATTEMPT_ID = "1b4e28ba-2fa1-4d2b-883f-0016d3cca427"
NO_COUNTS: dict[str, object] = {}


def summary_1_0_0(command: str, **changes: object) -> dict[str, object]:
    """A valid 1.0.0 summary of `command`, as Trial Folio 0.1.0 writes one."""
    run_counts = {
        "attempts": 1,
        "provider_requests": 1,
        "metrics_unavailable": 0,
        "warnings": 0,
        "cost": 5,
    }
    summary: dict[str, object] = {
        "schema_version": "1.0.0",
        "command": command,
        "trialfolio_version": "0.1.0",
        "outcome": "completed",
        "exit_code": 0,
        "ids": {"plan_hash": PLAN_HASH, "case_id": CASE_ID, "attempt_id": ATTEMPT_ID}
        if command in ("run", "demo")
        else {},
        "output_dir": "out",
        "outputs": {"manifest": "manifest.json", "report": "report.html"},
        "counts": run_counts if command in ("run", "demo") else NO_COUNTS,
        "statistical_validation": "not_assessed",
        "trading_readiness": "not_assessed",
        "error": None,
    }
    summary.update(changes)
    JsonSummary.model_validate_json(json.dumps(summary))
    return summary


SUMMARIES_1_0_0 = {
    "init": summary_1_0_0("init", output_dir=".", outputs={"configuration": "screen.yaml"}),
    "run": summary_1_0_0("run"),
    "run-failed": summary_1_0_0(
        "run",
        outcome="failed",
        exit_code=3,
        ids={},
        output_dir=None,
        outputs={},
        counts={
            "attempts": 0,
            "provider_requests": 0,
            "metrics_unavailable": 0,
            "warnings": 0,
            "cost": None,
        },
        error={"code": "config.invalid", "message": "screen.yaml isn't a valid configuration."},
    ),
    "report": summary_1_0_0("report", outputs={"report": "report.html"}),
    "demo": summary_1_0_0("demo"),
    "license": summary_1_0_0("license", output_dir=None, outputs={}),
}


@pytest.mark.parametrize("summary", SUMMARIES_1_0_0.values(), ids=SUMMARIES_1_0_0.keys())
def test_a_1_0_0_summary_is_valid_as_1_1_0(summary: dict[str, object]) -> None:
    """Each 1.0.0 key keeps its meaning, so a 1.0.0 summary of each 0.1.0 command, with its
    version changed, is a valid 1.1.0 summary. The 1.1.0 model generates the 1.1.0 schema, and
    the next test checks that the schema only adds to 1.0.0's."""
    JsonSummaryV1_1.model_validate_json(json.dumps(summary | {"schema_version": "1.1.0"}))


def test_the_json_summary_1_1_0_schema_only_adds_to_1_0_0() -> None:
    old, new = (json.loads(generate()[name]) for name in (SUMMARY_1_0_0, SUMMARY_1_1_0))
    changed = {
        name for name in old["properties"] if old["properties"][name] != new["properties"][name]
    }

    assert new["required"] == old["required"]
    assert new["properties"].keys() == old["properties"].keys()
    assert new["additionalProperties"] is False
    assert changed == {"schema_version", "command", "ids", "counts"}
    assert new["properties"]["command"]["enum"] == [*old["properties"]["command"]["enum"], "review"]
    old_ids, new_ids = old["$defs"]["SummaryIds"], new["$defs"]["SummaryIdsV1_1"]
    assert new_ids["properties"] == old_ids["properties"] | {
        "review_id": {"format": "uuid4", "title": "Review Id", "type": "string"}
    }
    assert "required" not in new_ids
    old_counts = old["properties"]["counts"]["anyOf"]
    assert new["properties"]["counts"]["anyOf"] == [
        old_counts[0],
        {"$ref": "#/$defs/ReviewCounts"},
        old_counts[1],
    ]
    for name, definition in old["$defs"].items():
        if name != "SummaryIds":
            assert new["$defs"][name] == definition, name


SUMMARY_1_1_0_SHA256 = "e0892988444d87e6ff8a0cb02fd72cec990ce3c354193308093fe75d4a3918e6"
"""The SHA-256 of `schemas/json-summary-1.1.0.schema.json` at the tag v0.2.0, written by hand:
`git show v0.2.0:schemas/json-summary-1.1.0.schema.json | shasum -a 256`."""


def test_the_json_summary_1_1_0_schema_keeps_v0_2_0_s_bytes() -> None:
    """It says what Trial Folio 0.2.0 prints, for scripts written against it (R03-AC16)."""
    committed = (ROOT / "schemas" / SUMMARY_1_1_0).read_bytes()

    assert hashlib.sha256(generate()[SUMMARY_1_1_0]).hexdigest() == SUMMARY_1_1_0_SHA256
    assert hashlib.sha256(committed).hexdigest() == SUMMARY_1_1_0_SHA256


REVIEW_ID = "6f1c2a3b-4d5e-4f60-8a71-b2c3d4e5f607"
REVIEW_COUNTS = {"results": 2, "settings_flagged": 1, "metrics_unavailable": 0, "warnings": 0}

SUMMARIES_1_1_0 = {
    **{
        name: summary | {"schema_version": "1.1.0", "trialfolio_version": "0.2.0"}
        for name, summary in SUMMARIES_1_0_0.items()
    },
    "review": summary_1_0_0("license")
    | {
        "schema_version": "1.1.0",
        "command": "review",
        "trialfolio_version": "0.2.0",
        "ids": {"review_id": REVIEW_ID},
        "output_dir": "reviews/holdings",
        "outputs": {
            "manifest": "manifest.json",
            "report": "report.html",
            "differences": "normalized/differences.csv",
        },
        "counts": REVIEW_COUNTS,
    },
    "review-failed": summary_1_0_0("license")
    | {
        "schema_version": "1.1.0",
        "command": "review",
        "trialfolio_version": "0.2.0",
        "outcome": "failed",
        "exit_code": 3,
        "output_dir": None,
        "outputs": {},
        "counts": REVIEW_COUNTS | {"settings_flagged": 0},
        "error": {"code": "input.not_a_run", "message": "Result 2's run isn't complete."},
    },
}


@pytest.mark.parametrize("summary", SUMMARIES_1_1_0.values(), ids=SUMMARIES_1_1_0.keys())
def test_a_1_1_0_summary_is_valid_as_1_2_0(summary: dict[str, object]) -> None:
    """Each 1.1.0 key keeps its meaning, so a 1.1.0 summary of each command, with its version
    changed, is a valid 1.2.0 summary (R03-AC16). The next test checks that 1.2.0's schema only
    adds to 1.1.0's."""
    JsonSummaryV1_1.model_validate_json(json.dumps(summary))

    JsonSummaryV1_2.model_validate_json(json.dumps(summary | {"schema_version": "1.2.0"}))


def test_the_json_summary_1_2_0_schema_only_adds_to_1_1_0() -> None:
    old, new = (json.loads(generate()[name]) for name in (SUMMARY_1_1_0, SUMMARY_1_2_0))
    changed = {
        name for name in old["properties"] if old["properties"][name] != new["properties"][name]
    }

    assert new["required"] == old["required"]
    assert new["properties"].keys() == old["properties"].keys() | {"cases"}
    assert new["additionalProperties"] is False
    assert changed == {"schema_version", "ids", "output_dir", "counts"}
    assert new["properties"]["output_dir"]["anyOf"] == old["properties"]["output_dir"]["anyOf"]
    assert new["properties"]["command"] == old["properties"]["command"]
    old_ids, new_ids = old["$defs"]["SummaryIdsV1_1"], new["$defs"]["SummaryIdsV1_2"]
    assert new_ids["properties"].keys() == old_ids["properties"].keys() | {
        "experiment_id",
        "session",
    }
    for name, definition in old_ids["properties"].items():
        assert new_ids["properties"][name] == definition, name
    assert "required" not in new_ids
    old_counts = old["properties"]["counts"]["anyOf"]
    assert new["properties"]["counts"]["anyOf"] == [
        *old_counts[:2],
        {"$ref": "#/$defs/ExperimentCounts"},
        old_counts[2],
    ]
    for name, definition in old["$defs"].items():
        if name != "SummaryIdsV1_1":
            assert new["$defs"][name] == definition, name
